### ISSUE TITLE
Oracle jdbc drivers for Java 7+

### ISSUE THREAD

**Issue by bcarlin** [waarp/WaarpCommon#80]
As it turned, Since the last release, we dropped support for Java 1.6. However, we still shipped Oracle JDBC drivers for Java 1.6 (ojdbc6.jar).

However, they support Java 1.7 and 1.8 from [Oracle 12c drivers](http://www.oracle.com/technetwork/database/features/jdbc/default-2280470.html).

According to their [compatibility matrix](http://www.oracle.com/technetwork/database/enterprise-edition/jdbc-faq-090281.html#01_02), this driver supports Oracle Database server version 11 and 12.

I have a few questions:
- Is it OK not to support Oracle Databases with versions <11?
- Is the migration straightforward?

Can anyone who knows Oracle provide some insight?

**Comment by fredericBregier** [comment]
- Considering we do support from Java 1.7, it means we could be compatible with at minimum ojdbc6 (compatible with JDK 6, 7 and 8) (whereas ojdbc5 is maximum at JDK5)
- According to this (http://www.oracle.com/us/support/library/lifetime-support-technology-069183.pdf?ssSourceSiteId=ocomfr ) it seems minimal version of Oracle is 8.1.7 from "Sustaining effort" point of view, but at minimum 11.2 from "Extended support"
- Some docs shows how to migrate (for instance this one from 9i to 11g: https://docs.oracle.com/cd/E11882_01/network.112/e10744/appd.htm#DBIMI358 )

Considering 2nd point, it might be reasonable to start to only support from 11.2, therefore using ojdbc6 for Oracle 11.2 and ojdbc7 for >= Oracle 12 (but using ojdbc6 allows also to use Oracle 9/10/11).
