### ISSUE TITLE
Oracle JDBC dependency issue

### ISSUE THREAD

**Issue by slauriere** [waarp/WaarpCommon#93]
While trying to run ``mvn clean install`` from a freshly checked out repository, master branch, I get the following error related to the Oracle JDBC lib:

``[ERROR] Failed to execute goal on project WaarpCommon: Could not resolve dependencies for project Waarp:WaarpCommon:jar:3.0.8: Could not find artifact Oracle:ojdbc6:jar:6 in waarp.releases (https://raw.github.com/waarp/WaarpMaven2/master/maven2) -> [Help 1]``

Would you know the origin of the problem? Thanks!

**Comment by slauriere** [comment]
I understand the Oracle JDBC jar has actually to be installed manually using ``mvn install:install-file...``. Closing this issue as fixed.

**Comment by bcarlin** [comment]
Indeed ! 
For clarification : the license of Oracle jdbc drivers prevents the redistribution of the jars, so it is not in any public maven repository.
The procedure is to download it from oracle website and to add it manually in maven cache with `mvn install:install-file` !
